---
- name: config_pgcluster.yml | Configuration PostgreSQL HA Cluster (based on "Patroni")
  hosts: postgres_cluster
  gather_facts: true
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"

    - name: Include system variables
      ansible.builtin.include_vars: "vars/system.yml"

    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"

    - name: Include LPP engine vars
      ansible.builtin.include_vars: "input/vars.yaml"
      ignore_errors: yes
      tags: always

    - name: '[Prepare] Set maintenance variable'
      ansible.builtin.set_fact:
        postgresql_cluster_maintenance: true

    - name: '[Prepare] Get Patroni Cluster Leader Node'
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}:{{ patroni_restapi_port }}/leader
        status_code: 200
      register: patroni_leader_result
      changed_when: false
      failed_when: false
      check_mode: false
      environment:
        no_proxy: "{{ inventory_hostname }}"

    # Stop, if Patroni is unavailable
    - name: The Patroni cluster is unhealthy
      ansible.builtin.fail:
        msg: "Patroni is unavailable on {{ ansible_hostname }}. Please check the cluster status."
      changed_when: false
      when: patroni_leader_result is undefined or patroni_leader_result.status == -1

    - name: '[Prepare] Add host to group "primary" (in-memory inventory)'
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: primary
        is_master: true
        postgresql_exists: true
      when: hostvars[item]['patroni_leader_result']['status'] == 200
      loop: "{{ groups['postgres_cluster'] }}"
      changed_when: false
      check_mode: false

    - name: '[Prepare] Add hosts to group "secondary" (in-memory inventory)'
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: secondary
        is_master: false
        postgresql_exists: true
      when: hostvars[item]['patroni_leader_result']['status'] != 200
      loop: "{{ groups['postgres_cluster'] }}"
      changed_when: false
      check_mode: false

    - name: "Print Patroni Cluster info"
      ansible.builtin.debug:
        msg:
          - "Cluster Name: {{ patroni_cluster_name }}"
          - "Cluster Leader: {{ ansible_hostname }}"
      when: inventory_hostname in groups['primary']

  roles:
    - role: pre-checks
      vars:
        minimal_ansible_version: 2.11.0
        timescale_minimal_pg_version: 12  # if enable_timescale is defined
  tags:
    - always

- name: config_pgcluster.yml | Configure Postgres Cluster
  hosts: 'primary:secondary'
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  any_errors_fatal: true
  environment: "{{ proxy_env | default({}) }}"
  handlers:
    - ansible.builtin.import_tasks: roles/patroni/handlers/main.yml
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
      tags: always

    - name: Include system variables
      ansible.builtin.include_vars: "vars/system.yml"
      tags: always

    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
      tags: always

    - name: Include LPP engine vars
      ansible.builtin.include_vars: "input/vars.yaml"
      ignore_errors: yes
      tags: always

  roles:

    - role: patroni/config

    - role: postgresql-extensions
      when: inventory_hostname in groups['primary']


- name: config_pgcluster.yml | Restart patroni on secondary after config settings if need
  hosts: secondary
  serial: 1  # restart replicas one by one
  gather_facts: false
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
      tags: always

    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
      tags: always

    - name: Include LPP engine vars
      ansible.builtin.include_vars: "input/vars.yaml"
      ignore_errors: yes
      tags: always

  tasks:
    - name: Stop read-only traffic
      ansible.builtin.include_role:
        name: update
        tasks_from: stop_traffic
      when:
        - pending_restart | bool
        - pg_pending_restart_settings | length > 0

    - name: Stop Services
      ansible.builtin.include_role:
        name: update
        tasks_from: stop_services
      when:
        - pending_restart | bool
        - pg_pending_restart_settings | length > 0

    - name: Start Services
      ansible.builtin.include_role:
        name: update
        tasks_from: start_services
      when:
        - pending_restart | bool
        - pg_pending_restart_settings | length > 0

    - name: Start read-only traffic
      ansible.builtin.include_role:
        name: update
        tasks_from: start_traffic
      when:
        - pending_restart | bool
        - pg_pending_restart_settings | length > 0
  tags:
    - patroni_conf

- name: config_pgcluster.yml | Restart patroni on master after config settings if need
  hosts: primary
  gather_facts: false
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  environment: "{{ proxy_env | default({}) }}"
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
      tags: always

    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
      tags: always

    - name: Include LPP engine vars
      ansible.builtin.include_vars: "input/vars.yaml"
      ignore_errors: yes
      tags: always

  tasks:
    - name: Switchover Patroni leader role
      ansible.builtin.include_role:
        name: update
        tasks_from: switchover
      when:
        - pending_restart | bool
        - pg_pending_restart_settings | length > 0

    - name: Stop read-only traffic
      ansible.builtin.include_role:
        name: update
        tasks_from: stop_traffic
      when:
        - pending_restart | bool
        - pg_pending_restart_settings | length > 0

    - name: Stop Services
      ansible.builtin.include_role:
        name: update
        tasks_from: stop_services
      when:
        - pending_restart | bool
        - pg_pending_restart_settings | length > 0

    - name: Start Services
      ansible.builtin.include_role:
        name: update
        tasks_from: start_services
      when:
        - pending_restart | bool
        - pg_pending_restart_settings | length > 0

    - name: Start read-only traffic
      ansible.builtin.include_role:
        name: update
        tasks_from: start_traffic
      when:
        - pending_restart | bool
        - pg_pending_restart_settings | length > 0
  tags:
    - patroni_conf

- name: config_pgcluster.yml | PostgreSQL Cluster Info
  hosts: primary
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
      tags: always

    - name: Include system variables
      ansible.builtin.include_vars: "vars/system.yml"
      tags: always

    - name: Include LPP engine vars
      ansible.builtin.include_vars: "input/vars.yaml"
      ignore_errors: yes
      tags: always

  roles:
    # finish (info)
    - role: deploy-finish
