---

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers

# users info
- block:
    - name: Get postgresql users list
      run_once: true
      become: true
      become_user: postgres
      ansible.builtin.command:
        "{{ postgresql_bin_dir }}/psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -Xc\"\\du\""
      register: users_result
      delegate_to: "{{ groups.master[0] }}"
      changed_when: false

    - name: PostgreSQL list of users
      run_once: true
      ansible.builtin.debug:
        var: users_result.stdout_lines
  ignore_errors: true
  tags: users, users_list, cluster_info, cluster_status, point_in_time_recovery

# databases info
- block:
    - name: Get postgresql database list
      run_once: true
      become: true
      become_user: postgres
      ansible.builtin.command:
        "{{ postgresql_bin_dir }}/psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -Xc
        \"
          SELECT
          d.datname as name,
          pg_get_userbyid(d.datdba) as owner,
          pg_encoding_to_char(d.encoding) as encoding,
          d.datcollate as collate,
          d.datctype as ctype,
          CASE
          WHEN has_database_privilege(d.datname, 'CONNECT')
          THEN pg_size_pretty(pg_database_size(d.datname))
          ELSE 'No Access'
          END
          size,
          t.spcname as tablespace
          FROM pg_catalog.pg_database d
          JOIN pg_catalog.pg_tablespace t
          ON d.dattablespace = t.oid
          WHERE NOT datistemplate
          ORDER BY 1
        \""
      register: dbs_result
      delegate_to: "{{ groups.master[0] }}"
      changed_when: false

    - name: PostgreSQL list of databases
      run_once: true
      ansible.builtin.debug:
        var: dbs_result.stdout_lines
  ignore_errors: true
  tags: databases, db_list, cluster_info, cluster_status, point_in_time_recovery

# cluster info
- block:
    - name: Check postgresql cluster health
      run_once: true
      become: true
      become_user: postgres
      ansible.builtin.command: patronictl -c /etc/patroni/patroni.yml list
      register: patronictl_result
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/local/bin"
      changed_when: false

    - name: PostgreSQL Cluster health
      run_once: true
      ansible.builtin.debug:
        var: patronictl_result.stdout_lines
  ignore_errors: true
  tags: patroni_status, cluster_info, cluster_status, point_in_time_recovery

- block:  # if cluster_vip is not defined
    - name: Create list of nodes
      run_once: true
      ansible.builtin.set_fact:
        haproxy_nodes: >-
          {{
            groups['balancers']
            | default([])
            | map('extract', hostvars, 'inventory_hostname')
            | join(',')
          }}
        postgres_cluster_nodes: >-
          {{
            groups['postgres_cluster']
            | default([])
            | map('extract', hostvars, 'inventory_hostname')
            | join(',')
          }}

    - name: PostgreSQL Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - address {{ haproxy_nodes }}
          - port {{ haproxy_listen_port.master }} (read/write) master
          - port {{ haproxy_listen_port.replicas }} (read only)  all replicas
          - port {{ haproxy_listen_port.replicas_sync }} (read only)  synchronous replica only
          - port {{ haproxy_listen_port.replicas_async }} (read only)  asynchronous replicas only
          - +------------------------------------------------+
      when:
        - with_haproxy_load_balancing | bool
        - synchronous_mode | bool

    - name: PostgreSQL Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - address {{ haproxy_nodes }}
          - port {{ haproxy_listen_port.master }} (read/write) master
          - port {{ haproxy_listen_port.replicas }} (read only)  all replicas
          - +------------------------------------------------+
      when:
        - with_haproxy_load_balancing | bool
        - not synchronous_mode | bool

    - name: PostgreSQL Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - address {{ postgres_cluster_nodes }}
          - port {{ postgresql_port }}
          - +------------------------------------------------+
      when:
        - not with_haproxy_load_balancing | bool
  ignore_errors: true
  tags: conn_info, cluster_info, cluster_status

...
