---
# Disable maintenance mode for HAProxy (Type A scheme)
# if 'pgbouncer_install' is 'true' and 'pgbouncer_pool_pause' is 'true'
- block:
    - name: Update haproxy conf file (enable http-checks)
      ansible.builtin.template:
        src: ../haproxy/templates/haproxy.cfg.j2 # use the haproxy role template
        dest: /etc/haproxy/haproxy.cfg
        owner: haproxy
        group: haproxy

    - name: Reload haproxy service
      ansible.builtin.systemd:
        name: haproxy
        state: reloaded

    - name: Start confd service
      ansible.builtin.service:
        name: confd
        state: started
  become: true
  become_user: root
  ignore_errors: true  # show the error and continue the playbook execution
  when:
    - with_haproxy_load_balancing | bool

...
